apiVersion: v1
kind: Secret
metadata:
  name: produtoapi-secret
  namespace: mcp-apis
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=postgres-produto;Port=5432;Database=produto_db;Username=postgres;Password=postgres;Gss Encryption Mode=Disable"
