apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "precoapi.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "precoapi.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Otel__Endpoint: {{ .Values.otel.endpoint | quote }}
  Otel__CaptureBody: {{ .Values.otel.captureBody | quote }}
