apiVersion: v1
kind: Service
metadata:
  name: precoapi
  namespace: mcp-apis
  labels:
    mcp-apis/indexed: "true"
  annotations:
    mcp-apis/base-url: "http://precoapi"
spec:
  selector:
    app: precoapi
  ports:
    - port: 80
      targetPort: 8080
