apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcpserver.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcpserver.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jaeger__BaseUrl: {{ .Values.jaeger.baseUrl | quote }}
  Kubernetes__Namespace: {{ .Values.kubernetes.namespace | quote }}
  Services__precoapi: {{ .Values.services.precoapi | quote }}
  Services__produtoapi: {{ .Values.services.produtoapi | quote }}
