apiVersion: v1
kind: ConfigMap
metadata:
  name: produtoapi-config
  namespace: mcp-apis
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Otel__Endpoint: http://jaeger:4317
  Otel__CaptureBody: "false"
  PrecoApi__BaseUrl: http://precoapi
