apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../aplicacao/mcpserver
labels:
  - pairs:
      app.kubernetes.io/part-of: mcp-apis
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
