apiVersion: v1
kind: Secret
metadata:
  name: {{ include "precoapi.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "precoapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__Default: "Host={{ .Values.db.host }};Port={{ .Values.db.port }};Database={{ .Values.db.name }};Username={{ .Values.db.user }};Password={{ .Values.db.password }}"
