{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "doctor-api-mcp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "doctor-api-mcp.labels" . | nindent 4 }}
{{- end }}
