apiVersion: v1
kind: Secret
metadata:
  name: precoapi-secret
  namespace: mcp-apis
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=postgres-preco;Port=5432;Database=preco_db;Username=postgres;Password=postgres;Gss Encryption Mode=Disable"
