apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-produto-init
  namespace: mcp-apis
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS products (
        id UUID PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        created_at TIMESTAMP
    );
