apiVersion: v1
kind: Secret
metadata:
  name: postgres-produto-secret
  namespace: mcp-apis
type: Opaque
data:
  # echo -n 'postgres' | base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_DB: cHJvZHV0b19kYg==
